/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_tobias_utils_util_AwakeUtils */

#ifndef _Included_de_tobias_utils_util_AwakeUtils
#define _Included_de_tobias_utils_util_AwakeUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_tobias_utils_util_AwakeUtils
 * Method:    lock
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_de_tobias_utils_util_AwakeUtils_lock
  (JNIEnv *, jobject);

/*
 * Class:     de_tobias_utils_util_AwakeUtils
 * Method:    unlock
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_de_tobias_utils_util_AwakeUtils_unlock
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
