/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_tobias_utils_util_SystemUtils */

#ifndef _Included_de_tobias_utils_util_SystemUtils
#define _Included_de_tobias_utils_util_SystemUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_tobias_utils_util_SystemUtils
 * Method:    getImageForFile_N
 * Signature: (Ljava/lang/String;)[B
 */
JNIEXPORT jbyteArray JNICALL Java_de_tobias_utils_util_SystemUtils_getImageForFile_1N
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
