/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class de_tobias_systemtray_menu_Menu */

#ifndef _Included_de_tobias_systemtray_menu_Menu
#define _Included_de_tobias_systemtray_menu_Menu
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_tobias_systemtray_menu_Menu
 * Method:    addItem_N
 * Signature: (Lde/tobias/systemtray/menu/MenuItem;Z)V
 */
JNIEXPORT void JNICALL Java_de_tobias_systemtray_menu_Menu_addItem_1N
  (JNIEnv *, jobject, jobject, jboolean);

/*
 * Class:     de_tobias_systemtray_menu_Menu
 * Method:    insertItem_N
 * Signature: (Lde/tobias/systemtray/menu/MenuItem;IZ)V
 */
JNIEXPORT void JNICALL Java_de_tobias_systemtray_menu_Menu_insertItem_1N
  (JNIEnv *, jobject, jobject, jint, jboolean);

/*
 * Class:     de_tobias_systemtray_menu_Menu
 * Method:    removeItem_N
 * Signature: (Lde/tobias/systemtray/menu/MenuItem;)V
 */
JNIEXPORT void JNICALL Java_de_tobias_systemtray_menu_Menu_removeItem_1N
  (JNIEnv *, jobject, jobject);

/*
 * Class:     de_tobias_systemtray_menu_Menu
 * Method:    removeItemAtIndex_N
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_de_tobias_systemtray_menu_Menu_removeItemAtIndex_1N
  (JNIEnv *, jobject, jint);

/*
 * Class:     de_tobias_systemtray_menu_Menu
 * Method:    clearMenu_N
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_de_tobias_systemtray_menu_Menu_clearMenu_1N
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
