/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_tobias_systemtray_SystemTrayItem */

#ifndef _Included_de_tobias_systemtray_SystemTrayItem
#define _Included_de_tobias_systemtray_SystemTrayItem
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_tobias_systemtray_SystemTrayItem
 * Method:    register_N
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_de_tobias_systemtray_SystemTrayItem_register_1N
  (JNIEnv *, jobject);

/*
 * Class:     de_tobias_systemtray_SystemTrayItem
 * Method:    removeItem_N
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_de_tobias_systemtray_SystemTrayItem_removeItem_1N
  (JNIEnv *, jobject);

/*
 * Class:     de_tobias_systemtray_SystemTrayItem
 * Method:    setMenu_N
 * Signature: (Lde/tobias/systemtray/menu/Menu;)V
 */
JNIEXPORT void JNICALL Java_de_tobias_systemtray_SystemTrayItem_setMenu_1N
  (JNIEnv *, jobject, jobject);

/*
 * Class:     de_tobias_systemtray_SystemTrayItem
 * Method:    setImage_N
 * Signature: ([B)V
 */
JNIEXPORT void JNICALL Java_de_tobias_systemtray_SystemTrayItem_setImage_1N
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     de_tobias_systemtray_SystemTrayItem
 * Method:    setToolTip_N
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_de_tobias_systemtray_SystemTrayItem_setToolTip_1N
  (JNIEnv *, jobject, jstring);

/*
 * Class:     de_tobias_systemtray_SystemTrayItem
 * Method:    deliverNotification
 * Signature: (Lde/tobias/systemtray/notification/Notification;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;[B)V
 */
JNIEXPORT void JNICALL Java_de_tobias_systemtray_SystemTrayItem_deliverNotification
  (JNIEnv *, jobject, jobject, jstring, jstring, jstring, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
