/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_tobias_systemtray_menu_SubMenu */

#ifndef _Included_de_tobias_systemtray_menu_SubMenu
#define _Included_de_tobias_systemtray_menu_SubMenu
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_tobias_systemtray_menu_SubMenu
 * Method:    addItem_N
 * Signature: (Lde/tobias/systemtray/menu/MenuItem;Z)V
 */
JNIEXPORT void JNICALL Java_de_tobias_systemtray_menu_SubMenu_addItem_1N
  (JNIEnv *, jobject, jobject, jboolean);

/*
 * Class:     de_tobias_systemtray_menu_SubMenu
 * Method:    insertItem_N
 * Signature: (Lde/tobias/systemtray/menu/MenuItem;IZ)V
 */
JNIEXPORT void JNICALL Java_de_tobias_systemtray_menu_SubMenu_insertItem_1N
  (JNIEnv *, jobject, jobject, jint, jboolean);

/*
 * Class:     de_tobias_systemtray_menu_SubMenu
 * Method:    removeItem_N
 * Signature: (Lde/tobias/systemtray/menu/MenuItem;)V
 */
JNIEXPORT void JNICALL Java_de_tobias_systemtray_menu_SubMenu_removeItem_1N
  (JNIEnv *, jobject, jobject);

/*
 * Class:     de_tobias_systemtray_menu_SubMenu
 * Method:    removeItemAtIndex_N
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_de_tobias_systemtray_menu_SubMenu_removeItemAtIndex_1N
  (JNIEnv *, jobject, jint);

/*
 * Class:     de_tobias_systemtray_menu_SubMenu
 * Method:    clearMenu_N
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_de_tobias_systemtray_menu_SubMenu_clearMenu_1N
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
