/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_tobias_systemtray_menu_MenuItem */

#ifndef _Included_de_tobias_systemtray_menu_MenuItem
#define _Included_de_tobias_systemtray_menu_MenuItem
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_tobias_systemtray_menu_MenuItem
 * Method:    register_N
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_de_tobias_systemtray_menu_MenuItem_register_1N
  (JNIEnv *, jobject);

/*
 * Class:     de_tobias_systemtray_menu_MenuItem
 * Method:    unregisterMenu_N
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_de_tobias_systemtray_menu_MenuItem_unregisterMenu_1N
  (JNIEnv *, jobject);

/*
 * Class:     de_tobias_systemtray_menu_MenuItem
 * Method:    setName_N
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_de_tobias_systemtray_menu_MenuItem_setName_1N
  (JNIEnv *, jobject, jstring);

/*
 * Class:     de_tobias_systemtray_menu_MenuItem
 * Method:    setEnabled_N
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_de_tobias_systemtray_menu_MenuItem_setEnabled_1N
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     de_tobias_systemtray_menu_MenuItem
 * Method:    setHidden_N
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_de_tobias_systemtray_menu_MenuItem_setHidden_1N
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     de_tobias_systemtray_menu_MenuItem
 * Method:    setImage_N
 * Signature: ([B)V
 */
JNIEXPORT void JNICALL Java_de_tobias_systemtray_menu_MenuItem_setImage_1N
  (JNIEnv *, jobject, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
