/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_tobias_systemtray_SystemTray */

#ifndef _Included_de_tobias_systemtray_SystemTray
#define _Included_de_tobias_systemtray_SystemTray
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_tobias_systemtray_SystemTray
 * Method:    startUp_N
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_de_tobias_systemtray_SystemTray_startUp_1N
  (JNIEnv *, jclass);

/*
 * Class:     de_tobias_systemtray_SystemTray
 * Method:    tearDown_N
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_de_tobias_systemtray_SystemTray_tearDown_1N
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
