/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_tobias_autostart_impl_OSXAutoStartNative */

#ifndef _Included_de_tobias_autostart_impl_OSXAutoStartNative
#define _Included_de_tobias_autostart_impl_OSXAutoStartNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_tobias_autostart_impl_OSXAutoStartNative
 * Method:    add_N
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_de_tobias_autostart_impl_OSXAutoStartNative_add_1N
  (JNIEnv *, jobject, jstring);

/*
 * Class:     de_tobias_autostart_impl_OSXAutoStartNative
 * Method:    isAutoStart_N
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_de_tobias_autostart_impl_OSXAutoStartNative_isAutoStart_1N
  (JNIEnv *, jobject, jstring);

/*
 * Class:     de_tobias_autostart_impl_OSXAutoStartNative
 * Method:    removeAutoStart_N
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_de_tobias_autostart_impl_OSXAutoStartNative_removeAutoStart_1N
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
